trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: TerraformInstaller@1
    inputs:
      terraformVersion: '1.5.0'

  - script: |
      terraform init
      terraform plan
      # terraform apply -auto-approve   # Uncomment when ready for deployment
    displayName: 'Terraform Plan/Apply'
